### ISSUE TITLE
[Pinpoint] Gson 플러그인 개발

### ISSUE THREAD

**Issue by lioolli** [naver/kaist-oss-course#10]
### 요구사항

Pinpoint에서 [Google Gson](https://code.google.com/p/google-gson/)을 프로파일링할 수 있도록 해 주는 플러그인을 작성한다.
- `Gson` 클래스의 `fromJson()` 메서드들과 `toJson()` 메서드들의 호출/종료 시간과 입력/출력 json 문자열의 길이를 기록하는 플러그인을 작성한다.
- 플러그인이 정상 동작하는지 검증하기 위한 테스트를 작성한다.
### 참고자료

Pinpoint Plugin: https://github.com/naver/pinpoint/tree/master/plugins
Pinpoint Plugin Test: https://github.com/naver/pinpoint/tree/master/agent

**Comment by nstopkimsk** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
김성관(sungkwan.kim@naverco...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [kaist-oss-course] [Pinpoint] Gson 플러그인 개발 (#10)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
김성관(sungkwan.kim@naverco...) 님이 남기신 메시지 입니다.
--------------------------------------------
[부재기간 : 2015-04-06 00:00 ~ 2015-04-10 23:59 GMT +09:00]<br>일본 출장 중입니다. 업무시간 중간 중간 대응 가능한 것은 대응하도록 하겠습니다. <br>급한 용무는 김진녕님에게 부탁드립니다.  <br>
--------------------------------------------

**Comment by yous** [comment]
제가 진행해 보겠습니다.

**Comment by lioolli** [comment]
@yous 
넵 일단 Gson 사용하면서 api들 확인해 보고 계시면 될 것 같습니다.
Gson은 API가 워낙 심플해서 어떤 메서드를 잡아야 할 지 이미 답이 나와 있으니 편하게 보고 계세요~

**Comment by yous** [comment]
@lioolli 현재 Pinpoint 설치는 해두었는데, 혹시 이미 작성된 다른 플러그인을 간단하게 사용해볼 수 있는 방법이 있을까요?

**Comment by lioolli** [comment]
quickstart를 실행해 보시는 것이 핀포인트를 실행시켜 볼 수 있는 가장 간단한 방법입니다.
quickstart에서 Tomcat을 사용하기 때문에 tomcat 플러그인의 동작을 확인해 보실 수 있습니다.

**Comment by lioolli** [comment]
핀포인트 플러그인 작성 예제를 올려놨습니다.
일단 한 번 살펴보시고 궁금하신 점 있으시면 문의 주세요~
https://github.com/lioolli/pinpoint-plugin-sample

**Comment by yous** [comment]
감사합니다, 곧 진행 상황 알려드릴 수 있도록 하겠습니다.

**Comment by yous** [comment]
@lioolli 안녕하세요, Gson의 `fromJson()`과 `toJson()`의 경우 generic이 쓰여서 `MethodFilter`를 이용해야 할 것 같은데요, 두 이름 외에 `toJsonTree()`도 기록해야 할까요?

또, `fromJson()`에선 다른 `fromJson()`을, `toJson()`에선 다른 `toJson()`을, `toJsonTree()`에선 다른 `toJson()`과 `toJsonTree()`를 호출하고 있는데, 이런 구조일 경우 `MethodFilter`로 `fromJson`, `toJson`, `toJsonTree`의 이름만 비교해서 모두 기록해도 상관없을까요? 아니면 내부에서 불린 것만 제외하고 기록할 수도 있는 것인가요?

**Comment by lioolli** [comment]
- generic이 아니라 오버로딩 말씀하시는 거죠? : ) 오버로딩 된 메서드들에 같은 인터셉터를 거실 거라면MethodFilter 쓰시는 게 간단할 것 같습니다.
- toJsonTree()는 일단 제외하고 가도 될 것 같습니다.
- 중복 추적을 피하려면 샘플 플러그인에서 Sample3_Use_Interceptor_Group_To_Prevent_Redundant_Trace_IT를 참고하시면 될 것 같습니다.

**Comment by yous** [comment]
- 아하 네, 오버로딩도 있고, 일반 메소드에도 `Class<T>` 등이 쓰여서 `MethodFilter`를 써야 할 거라고 생각했습니다. https://github.com/google/gson/blob/master/gson/src/main/java/com/google/gson/Gson.java
- 알겠습니다.
- 말씀하신 샘플을 봤습니다. 그렇다면 여러 종류의 `fromJson`을 한 그룹에, 여러 종류의 `toJson`을 한 그룹에 묶어도 괜찮을까요?

**Comment by lioolli** [comment]
generic을 쓰면 컴파일러에 의해 bridge method가 추가되긴 하는데 거기까진 신경쓰지 않으셔도 될 거에요. bridge method가 어차피 바로 원래 메서드 호출하는 게 전부라서요.

그리고 그룹은 말씀하신 대로 묶으면 될 것 같습니다~

**Comment by yous** [comment]
아하, 그렇군요. 설명 감사합니다. :smiley:

**Comment by yous** [comment]
안녕하세요, `toJson(Object src, Appendable writer)` 등의 경우 `writer`에 JSON 결과를 쓰고 있어서 결과 문자열의 길이를 한 번에 알아낼 방법이 없습니다. 이 경우 어떤 식으로 처리하는 것이 좋을까요? `fromJson(Reader json, Class<T> classofT)`처럼 이 경우는 그냥 기록하지 않는 것이 나을까요?

**Comment by yous** [comment]
추가로, `verifyTraceBlock`을 통해 annotation 테스트를 하고 있는데요, 다음과 같은 에러 메시지가 나옵니다.

```
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 4.541 sec <<< FAILURE! - in com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT
test[:system:7](com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT)  Time elapsed: 0.438 sec  <<< ERROR!
com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.AssertionError: Expected [1] annotations but was [3], expected: SpanEvent(serviceType: 5099, apiId: -5, rpc: null, endPoint: null, remoteAddr: null, destinationId: null, annotations: [JSON_LENGTH=8]), was: (serviceType: 5099, apiId: -5, rpc: null, endPoint: null, destinationId: null, [-1=Pinpoint, -2=class java.lang.String, 9998=8])
    at com.navercorp.pinpoint.test.PluginTestAgent.verifySpan(PluginTestAgent.java:517)
    at com.navercorp.pinpoint.test.PluginTestAgent.verifyTraceBlock(PluginTestAgent.java:227)
    at com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT.verifyTraceBlockAnnotation(GsonMethodFilterIT.java:132)
    at com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT.test(GsonMethodFilterIT.java:111)

test[:child:7](com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT)  Time elapsed: 0.382 sec  <<< ERROR!
com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.AssertionError: Expected [1] annotations but was [3], expected: SpanEvent(serviceType: 5099, apiId: -5, rpc: null, endPoint: null, remoteAddr: null, destinationId: null, annotations: [JSON_LENGTH=8]), was: (serviceType: 5099, apiId: -5, rpc: null, endPoint: null, destinationId: null, [-1=Pinpoint, -2=class java.lang.String, 9998=8])
    at com.navercorp.pinpoint.test.PluginTestAgent.verifySpan(PluginTestAgent.java:517)
    at com.navercorp.pinpoint.test.PluginTestAgent.verifyTraceBlock(PluginTestAgent.java:227)
    at com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT.verifyTraceBlockAnnotation(GsonMethodFilterIT.java:132)
    at com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT.test(GsonMethodFilterIT.java:111)
```

5099와 9998은 각각 임의로 정한 `ServiceType` 코드와 `AnnotationKey`의 코드이고요, `JSON_LENGTH`가 annotation의 키입니다. -1과 -2에 해당하는 annotation이 추가로 있어서 실패하고 있는 것 같은데, 저 두 가지 annotation이 원래 추가되는 건가요? 그렇다면 어떤 식으로 테스트를 고쳐야 할까요?

다음은 테스트 코드 중 일부입니다.

``` java
final String json = "Pinpoint";
final int json_length = json.length();
final String serviceType = "GSON";
final String annotationKeyName = "JSON_LENGTH";
final PluginTestVerifier.ExpectedAnnotation expectedAnnotation = PluginTestVerifier.ExpectedAnnotation.annotation(annotationKeyName, json_length);
final Gson gson = new Gson();

gson.fromJson(json, String.class);
Method fromJson1 = Gson.class.getDeclaredMethod("fromJson", String.class, Class.class);
verifyTraceBlockAnnotation(verifier, serviceType, fromJson1, expectedAnnotation);
```

``` java
private void verifyTraceBlockAnnotation(PluginTestVerifier verifier, String serviceType, Member api, PluginTestVerifier.ExpectedAnnotation annotation) {
    verifier.verifyTraceBlock(PluginTestVerifier.BlockType.EVENT, serviceType, api, null, null, null, null, annotation);
}
```

**Comment by lioolli** [comment]
- 일단 String이 아닌 다른 타입을 사용해서 json을 읽고 쓰는 경우에는 길이 기록을 건너뛰도록 하겠습니다.
- 인터셉터에서 recordApi 호출할 때 전달인자를 함께 넘기면 자동으로 순서대로 -1, -2, ...를 키로 해서 기록됩니다. 인자를 기록할 필요는 없으니 MethodDescriptor만을 넘겨서 불러 주세요.

**Comment by yous** [comment]
아, `recordApi()`에 `args`를 넘겨서 그랬던 거군요. 잘 알겠습니다.

테스트를 돌려 보니 다음과 같은 에러가 나옵니다.

```
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 6.265 sec <<< FAILURE! - in com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT
test[:system:7](com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT)  Time elapsed: 0.721 sec  <<< ERROR!
com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.AssertionError: Expected a SpanEvent with apiId[-6] but was [6]. expected: SpanEvent(serviceType: 5099, apiId: -6, rpc: null, endPoint: null, remoteAddr: null, destinationId: null, annotations: []), was: (serviceType: 5099, apiId: 6, rpc: null, endPoint: null, destinationId: null, [])
    at com.navercorp.pinpoint.test.PluginTestAgent.verifySpan(PluginTestAgent.java:492)
    at com.navercorp.pinpoint.test.PluginTestAgent.verifyApi(PluginTestAgent.java:569)
    at com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT.test(GsonMethodFilterIT.java:113)

test[:child:7](com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT)  Time elapsed: 0.621 sec  <<< ERROR!
com.navercorp.pinpoint.test.plugin.PinpointPluginTestException: java.lang.AssertionError: Expected a SpanEvent with apiId[-6] but was [6]. expected: SpanEvent(serviceType: 5099, apiId: -6, rpc: null, endPoint: null, remoteAddr: null, destinationId: null, annotations: []), was: (serviceType: 5099, apiId: 6, rpc: null, endPoint: null, destinationId: null, [])
    at com.navercorp.pinpoint.test.PluginTestAgent.verifySpan(PluginTestAgent.java:492)
    at com.navercorp.pinpoint.test.PluginTestAgent.verifyApi(PluginTestAgent.java:569)
    at com.navercorp.pinpoint.plugin.gson.GsonMethodFilterIT.test(GsonMethodFilterIT.java:113)
```

API 목록은 다음과 같습니다.

```
API(15):
-8: com.google.gson.Gson.fromJson(com.google.gson.JsonElement json, java.lang.reflect.Type typeOfT):872
-7: com.google.gson.Gson.fromJson(com.google.gson.stream.JsonReader reader, java.lang.reflect.Type typeOfT):802
-6: com.google.gson.Gson.fromJson(java.io.Reader json, java.lang.Class classOfT):747
-5: com.google.gson.Gson.fromJson(java.lang.String json, java.lang.Class classOfT):696
-4: com.google.gson.Gson.toJson(com.google.gson.JsonElement jsonElement, java.lang.Appendable writer):633
-3: com.google.gson.Gson.toJson(java.lang.Object src, java.lang.reflect.Type typeOfSrc, com.google.gson.stream.JsonWriter writer):592
-2: com.google.gson.Gson.toJson(java.lang.Object src, java.lang.Appendable writer):553
-1: com.google.gson.Gson.toJson(java.lang.Object src):511
1: com.google.gson.Gson.toJson(java.lang.Object src, java.lang.reflect.Type typeOfSrc):533
2: com.google.gson.Gson.toJson(java.lang.Object src, java.lang.reflect.Type typeOfSrc, java.lang.Appendable writer):578
3: com.google.gson.Gson.toJson(com.google.gson.JsonElement jsonElement):618
4: com.google.gson.Gson.toJson(com.google.gson.JsonElement jsonElement, com.google.gson.stream.JsonWriter writer):661
5: com.google.gson.Gson.fromJson(java.lang.String json, java.lang.reflect.Type typeOfT):720
6: com.google.gson.Gson.fromJson(java.io.Reader json, java.lang.reflect.Type typeOfT):774
7: com.google.gson.Gson.fromJson(com.google.gson.JsonElement json, java.lang.Class classOfT):848
```

에러가 발생하는 부분의 코드는 다음과 같습니다.

``` java
gson.fromJson(new StringReader(json), String.class); // fromJson3
gson.fromJson(new StringReader(json), (Type) String.class); // fromJson4
gson.fromJson(new JsonReader(new StringReader(json)), String.class); // fromJson5
Method fromJson3 = Gson.class.getDeclaredMethod("fromJson", Reader.class, Class.class);
Method fromJson4 = Gson.class.getDeclaredMethod("fromJson", Reader.class, Type.class);
Method fromJson5 = Gson.class.getDeclaredMethod("fromJson", JsonReader.class, Type.class);
verifier.verifyApi(serviceType, fromJson3);
verifier.verifyApi(serviceType, fromJson4);
verifier.verifyApi(serviceType, fromJson5);
```

113번째 줄에 해당하는 부분이 `fromJson3`을 verify 하는 부분이고, 에러 메시지에선 `fromJson4`가 호출되었다고 나오고 있습니다. `Class.class`와 `Type.class`가 제대로 구분되지 않고 있는 것인가요? `fromJson3` 내부에선 `fromJson5`, 즉 API -7이 호출되기 때문에 직접적인 관련은 없을 것 같습니다.

**Comment by lioolli** [comment]
음 로그에 보면 API 목록 다음에 출력되는 TRACES 목록이 있는데 그것도 좀 첨부해 주시겠어요?

**Comment by yous** [comment]
`TSpanEvent`가 나오는 이 목록인가요?

```
TSpanEvent(sequence:0, startElapsed:-2066423786, endElapsed:12, serviceType:5099, annotations:[TAnnotation(key:9998, value:<TAnnotationValue intValue:8>)], depth:1, apiId:-5)
TSpanEvent(sequence:1, startElapsed:-2066423786, endElapsed:11, serviceType:5099, annotations:[TAnnotation(key:9998, value:<TAnnotationValue intValue:8>)], depth:2, apiId:5)
TSpanEvent(sequence:2, startElapsed:-2066423785, endElapsed:4, serviceType:5099, depth:3, apiId:6)
TSpanEvent(sequence:3, startElapsed:-2066423785, endElapsed:4, serviceType:5099, depth:4, apiId:-7)
TSpanEvent(sequence:4, startElapsed:-2066423774, endElapsed:1, serviceType:5099, annotations:[TAnnotation(key:9998, value:<TAnnotationValue intValue:8>)], depth:1, apiId:5)
TSpanEvent(sequence:5, startElapsed:-2066423774, endElapsed:1, serviceType:5099, depth:2, apiId:6)
TSpanEvent(sequence:6, startElapsed:-2066423773, serviceType:5099, depth:3, apiId:-7)
TSpanEvent(sequence:7, startElapsed:-2066423772, serviceType:5099, depth:1, apiId:-6)
TSpanEvent(sequence:8, startElapsed:-2066423772, serviceType:5099, depth:2, apiId:-7)
TSpanEvent(sequence:9, startElapsed:-2066423772, endElapsed:1, serviceType:5099, depth:1, apiId:6)
TSpanEvent(sequence:10, startElapsed:-2066423771, serviceType:5099, depth:2, apiId:-7)
TSpanEvent(sequence:11, startElapsed:-2066423771, endElapsed:1, serviceType:5099, depth:1, apiId:-7)
TSpanEvent(sequence:12, startElapsed:-2066423770, endElapsed:2, serviceType:5099, apiId:7)
TSpanEvent(sequence:13, startElapsed:-2066423770, endElapsed:2, serviceType:5099, depth:2, apiId:-8)
TSpanEvent(sequence:14, startElapsed:-2066423769, endElapsed:1, serviceType:5099, depth:3, apiId:-7)
TSpanEvent(sequence:15, startElapsed:-2066423768, endElapsed:1, serviceType:5099, depth:1, apiId:-8)
TSpanEvent(sequence:16, startElapsed:-2066423767, serviceType:5099, depth:2, apiId:-7)
TSpanEvent(sequence:17, startElapsed:-2066423767, endElapsed:5, serviceType:5099, annotations:[TAnnotation(key:9998, value:<TAnnotationValue intValue:10>)], depth:1, apiId:-1)
TSpanEvent(sequence:18, startElapsed:-2066423766, endElapsed:4, serviceType:5099, annotations:[TAnnotation(key:9998, value:<TAnnotationValue intValue:10>)], depth:2, apiId:1)
TSpanEvent(sequence:19, startElapsed:-2066423766, endElapsed:3, serviceType:5099, depth:3, apiId:2)
TSpanEvent(sequence:20, startElapsed:-2066423763, serviceType:5099, depth:4, apiId:-3)
TSpanEvent(sequence:21, startElapsed:-2066423762, endElapsed:1, serviceType:5099, annotations:[TAnnotation(key:9998, value:<TAnnotationValue intValue:10>)], depth:1, apiId:1)
TSpanEvent(sequence:22, startElapsed:-2066423762, endElapsed:1, serviceType:5099, depth:2, apiId:2)
TSpanEvent(sequence:23, startElapsed:-2066423761, serviceType:5099, depth:3, apiId:-3)
TSpanEvent(sequence:24, startElapsed:-2066423760, endElapsed:1, serviceType:5099, depth:1, apiId:-2)
TSpanEvent(sequence:25, startElapsed:-2066423760, endElapsed:1, serviceType:5099, depth:2, apiId:2)
TSpanEvent(sequence:26, startElapsed:-2066423760, serviceType:5099, depth:3, apiId:-3)
TSpanEvent(sequence:27, startElapsed:-2066423759, endElapsed:1, serviceType:5099, depth:1, apiId:2)
TSpanEvent(sequence:28, startElapsed:-2066423759, endElapsed:1, serviceType:5099, depth:2, apiId:-3)
TSpanEvent(sequence:29, startElapsed:-2066423758, endElapsed:1, serviceType:5099, depth:1, apiId:-3)
TSpanEvent(sequence:30, startElapsed:-2066423757, endElapsed:1, serviceType:5099, annotations:[TAnnotation(key:9998, value:<TAnnotationValue intValue:10>)], apiId:3)
TSpanEvent(sequence:31, startElapsed:-2066423757, endElapsed:1, serviceType:5099, depth:2, apiId:-4)
TSpanEvent(sequence:32, startElapsed:-2066423757, endElapsed:1, serviceType:5099, depth:3, apiId:4)
TSpanEvent(sequence:33, startElapsed:-2066423755, endElapsed:1, serviceType:5099, depth:1, apiId:-4)
TSpanEvent(sequence:34, startElapsed:-2066423755, serviceType:5099, depth:2, apiId:4)
TSpanEvent(sequence:35, startElapsed:-2066423754, serviceType:5099, depth:1, apiId:4)
```

전체 테스트 코드는 다음과 같습니다.

``` java
final String json = "Pinpoint";
final int json_length = json.length();
final String serviceType = "GSON";
final String annotationKeyName = "JSON_LENGTH";
final PluginTestVerifier.ExpectedAnnotation expectedAnnotation = PluginTestVerifier.ExpectedAnnotation.annotation(annotationKeyName, json_length);
final Gson gson = new Gson();
final JsonElement jsonElement = new JsonParser().parse(json);

/**
 * @see Gson#fromJson(String, Class)
 * @see Gson#fromJson(String, Type)
 * @see Gson#fromJson(Reader, Class)
 * @see Gson#fromJson(Reader, Type)
 * @see Gson#fromJson(JsonReader, Type)
 * @see Gson#fromJson(JsonElement, Class)
 * @see Gson#fromJson(JsonElement, Type)
 */
gson.fromJson(json, String.class);
gson.fromJson(json, (Type) String.class);
gson.fromJson(new StringReader(json), (Class) String.class);
gson.fromJson(new StringReader(json), (Type) String.class);
gson.fromJson(new JsonReader(new StringReader(json)), String.class);
gson.fromJson(jsonElement, String.class);
gson.fromJson(jsonElement, (Type) String.class);

Method fromJson1 = Gson.class.getDeclaredMethod("fromJson", String.class, Class.class);
Method fromJson2 = Gson.class.getDeclaredMethod("fromJson", String.class, Type.class);
Method fromJson3 = Gson.class.getDeclaredMethod("fromJson", Reader.class, Class.class);
Method fromJson4 = Gson.class.getDeclaredMethod("fromJson", Reader.class, Type.class);
Method fromJson5 = Gson.class.getDeclaredMethod("fromJson", JsonReader.class, Type.class);
Method fromJson6 = Gson.class.getDeclaredMethod("fromJson", JsonElement.class, Class.class);
Method fromJson7 = Gson.class.getDeclaredMethod("fromJson", JsonElement.class, Type.class);

/**
 * @see Gson#toJson(Object)
 * @see Gson#toJson(Object, Type)
 * @see Gson#toJson(Object, Appendable)
 * @see Gson#toJson(Object, Type, Appendable)
 * @see Gson#toJson(Object, Type, JsonWriter)
 * @see Gson#toJson(JsonElement)
 * @see Gson#toJson(JsonElement, Appendable)
 * @see Gson#toJson(JsonElement, JsonWriter)
 */
gson.toJson(json);
gson.toJson(json, String.class);
gson.toJson(json, new StringWriter());
gson.toJson(json, String.class, new StringWriter());
gson.toJson(json, String.class, new JsonWriter(new StringWriter()));
gson.toJson(jsonElement);
gson.toJson(jsonElement, new StringWriter());
gson.toJson(jsonElement, new JsonWriter(new StringWriter()));

Method toJson1 = Gson.class.getDeclaredMethod("toJson", Object.class);
Method toJson2 = Gson.class.getDeclaredMethod("toJson", Object.class, Type.class);
Method toJson3 = Gson.class.getDeclaredMethod("toJson", Object.class, Appendable.class);
Method toJson4 = Gson.class.getDeclaredMethod("toJson", Object.class, Type.class, Appendable.class);
Method toJson5 = Gson.class.getDeclaredMethod("toJson", Object.class, Type.class, JsonWriter.class);
Method toJson6 = Gson.class.getDeclaredMethod("toJson", JsonElement.class);
Method toJson7 = Gson.class.getDeclaredMethod("toJson", JsonElement.class, Appendable.class);
Method toJson8 = Gson.class.getDeclaredMethod("toJson", JsonElement.class, JsonWriter.class);

PluginTestVerifier verifier = PluginTestVerifierHolder.getInstance();
verifier.printCache(System.out);
verifier.printBlocks(System.out);

verifyTraceBlockAnnotation(verifier, serviceType, fromJson1, expectedAnnotation);
verifyTraceBlockAnnotation(verifier, serviceType, fromJson2, expectedAnnotation);
verifier.verifyApi(serviceType, fromJson3);
verifier.verifyApi(serviceType, fromJson4);
verifier.verifyApi(serviceType, fromJson5);
verifier.verifyApi(serviceType, fromJson6);
verifier.verifyApi(serviceType, fromJson7);

verifyTraceBlockAnnotation(verifier, serviceType, toJson1, expectedAnnotation);
verifyTraceBlockAnnotation(verifier, serviceType, toJson2, expectedAnnotation);
verifier.verifyApi(serviceType, toJson3);
verifier.verifyApi(serviceType, toJson4);
verifier.verifyApi(serviceType, toJson5);
verifyTraceBlockAnnotation(verifier, serviceType, toJson6, expectedAnnotation);
verifier.verifyApi(serviceType, toJson7);
verifier.verifyApi(serviceType, toJson8);

verifier.verifyTraceBlockCount(0);
```

**Comment by lioolli** [comment]
네 TSpanEvent들이 기록된 데이터들인데, 보시면 테스트 코드에서 메서드 호출한 건수보다 훨씬 많은 건수가 기록되어 있죠. 내부에서 서로 호출한 것도 모두 기록된 것 같은데요, 우선 앞에서 말씀하신 대로 인터셉터그룹 지정 하셨는지 확인 부탁드려요~

**Comment by yous** [comment]
아, 그러면 `editMethods()`를 통해 `MethodFilter`를 설정하면서 인터셉터 그룹을 정해야 할 텐데요, 그러면 `fromJson`을 위한 `MethodFilter`와 `toJson`을 위한 `MethodFilter`를 각각 만들어서 따로 따로 `editMethods()`를 호출하면 되는 것인가요?

**Comment by lioolli** [comment]
지금 경우에는 fromJson과 toJson이 다른 그룹이어야 할 필요는 없을 것 같습니다. 그냥 다 같은 그룹에 넣으셔도 될 것 같아요-

**Comment by yous** [comment]
인터셉터의 그룹을 지정하고 `mvn verify`가 성공하는 것을 확인했습니다. 풀 리퀘스트를 만들어 두었으니 한 번 봐 주시길 부탁드립니다. naver/pinpoint#462

**Comment by beanmilk** [comment]
@yous 차영님, 한 학기동안 수고하셨습니다! :+1:
