### ISSUE TITLE
[ARCUS] hubble에서 조회 범위 지정 기능 개선

### ISSUE THREAD

**Issue by jhpark816** [naver/kaist-oss-course#58]
Arcus hubble(https://github.com/naver/arcus-hubble) 에서 
아래와 같이 조회 시작 시간과 조회 기간을 자유롭게 설정할 수 있도록 개선한다.
- 조회 시작 시간 + 조회 기간(30분, 1시간, 6시간, 1일, ...)

Hubble main page에서 hubble 로고 바로 아래에 있는 `select` 버튼이 정상 동작할 수 있게 수정한다.

**Comment by diridiri** [comment]
제가 한번 해보겠습니다.

**Comment by lsj1888** [comment]
@diridiri 진행해보시고, 잘 안되거나 궁금하신 내용있으면 이곳에 질문 올려주세요.

**Comment by jhpark816** [comment]
조만간 `develop` 브랜치가 준비될 예정인데요.
`develop` 브랜치 기준으로 작업하시고, pull request도 `develop` 브랜치 기준으로 보내주세요.

**Comment by MinWooJin** [comment]
arcus-hubble develop 브랜치 준비가 완료 되었습니다.
develop 브랜치 기준으로 작업하시고, pull request도 develop 브랜치 기준으로 보내주세요.

**Comment by diridiri** [comment]
질문이 있습니다.
ubuntu 14.04 lts에서 작업하고있습니다.
hubblemon에 아커스를 붙이고 있는데 local.sample.json으로 quicksetup시 arcus stat을 수집해오는 도중 listener에서 division by zero exception이 나면서 아무 차트도 나오지 않습니다.
찾아보니 collect_server의 alarm.py의 check함수에서 lambda_func을 돌리다 exception이 나는 것으로 보이는데요.. 음 curr_item과 limits[idx]가 잘 넘어오는걸로 봐서 연결은 잘 되어있는 것 같습니다.
어디서 문제가 나는건지 혹시 알 수 있을까요???

**Comment by MinWooJin** [comment]
@diridiri 
질문과 현상을 구분해서 질문을 명확하게 정리해주시면 정확한 답변을 드리는데 좋을것 같습니다.
추가로, arcus-hubble에 관련된 이슈인데 hubblemon을 사용하는 다른 이유가 있을까요?

**Comment by diridiri** [comment]
hubblemon은 개인적 용도로도 사용해보려고 합니다.  hubblemon 문제는 나중에 여쭤보겠습니다.ㅠㅠ

그리고 arcus-hubble 관련 질문이 있습니다.

docker 에서 Ubuntu 12.04를 세팅하고 arcus-hubble을 모두 build했는데요,

$COLLECTD_HOME/sbin/collectd -C $COLLECTD_HOME/etc/collectd-listener-5s.conf 를 실행했을 때

[2016-05-24 06:24:09] network plugin: getaddrinfo (, 25828) failed: Name or service not known
[2016-05-24 06:24:09] network plugin: network_config_add_listen: sockent_open failed.

라고 로그가 뜨면서 종료됩니다. 

어떤 문제인지 알 수 있을까요..?

+) /etc/hosts파일은 다음과 같습니다.
172.17.0.7      a595af52a7eb
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

**Comment by diridiri** [comment]
collectd-listener-5s.conf  파일의 주소를 입력 안했었네요
수정했습니다.

**Comment by diridiri** [comment]
안녕하세요
질문이 있습니다.

Docker에서 ubuntu 12.04 설치해서 develop 브랜치의 arcus-hubble을 빌드했습니다.

./start.sh 실행 이후 curl -i localhost:8080로 nodejs서버가 도는것을 확인했는데요, 실제 서버 주소인 143.248.47.203:8080으로 라우팅되지는 않는 것 같습니다.

혹시 설정 방법을 알 수 있을까요?

감사합니다.

**Comment by minkikim89** [comment]
@diridiri 
hubble은 env.sh에 설정을 하고 build를 진행할 시에 쉘 스크립트를 통해 자동으로 설정이 되는 구조를 취하고 있습니다. 문제가 생기는 이유를 바로 알기가 쉽지 않네요. 기본적으로 hubble 웹에 대한 설정은 conf/conf-view에 있습니다. 하지만 이 부분에서 설정해주는 것은 port만으로, 현 상황과는 무관한 것으로 보입니다.
혹시나 싶은 것은 docker를 사용하셨다고 하니 혹시 포트포워딩에 관련된 문제가 아닐까 싶습니다. docker로 인해 일어날 수 있는 상황에 대해 한번 고려해보시고 다시 코멘트 주시면 감사하겠습니다.

**Comment by diridiri** [comment]
docker에서 port를 할당하지 않아 발생하는 문제였습니다.
docker에서도 똑같이 8080포트를 열어주니 해결되었습니다.
감사합니다.

**Comment by ghost** [comment]
이슈를 변경하여 팀원으로 참여하게 되었습니다.

**Comment by diridiri** [comment]
안녕하세요 빌드관련 질문이 늦어져서 죄송합니다..
arcus-hubble을 ubuntu 12.04에서 세팅했습니다. 

export COLLECTD_HOME=$HOME/arcus-collectd
export ARCUS_HUBBLE_HOME=$HOME/vendor/arcus-hubble
$COLLECTD_HOME/sbin/collectd -C $COLLECTD_HOME/etc/collectd-listener-5s.conf
$COLLECTD_HOME/sbin/collectd -C $COLLECTD_HOME/etc/collectd-arcus.conf
$COLLECTD_HOME/sbin/collectd -C $COLLECTD_HOME/etc/collectd-arcus-prefix.conf
$ARCUS_HUBBLE_HOME/start.sh
를 실행한 후

hubble_data가 수집되는 것까지 보았습니다만 arcus탭에 아무것도 뜨지 않아서 질문 드립니다.
혹시 arcus-hubble외에 arcus도 추가로 설치해야하는지 혹은 따로 설치해야하는 것이 있는지 알고 싶습니다. 
감사합니다.

**Comment by minkikim89** [comment]
@diridiri 
arcus 탭이라고 말씀하신 부분은 arcus_stat과 arcus_prefix를 말하시는 건가요? 이 부분들은 둘 다 arcus의 통계치를 보여주는 부분입니다. arcus를 설치하시고 실행하셔야합니다.

**Comment by ghost** [comment]
@minkikim89
네, 감사합니다.
우선 arcus docker와 arcus-hubble docker를 설치한 후에 막히는 부분이 있으면 다시 질문드리겠습니다.

**Comment by ghost** [comment]
@minkikim89 
연휴에 계속해서 질문드려 죄송합니다.
arcus-hubble와 arcus를 각각 다른 docker에서 설치한 후에  arcus docker에 link를 걸고  arcus-hubble을 실행하려고 합니다.
그래서 arcus-hubble의 conf파일들을 바꾸려고 하는데 어떤 conf 파일을 바꿔야 하는지 알 수 있을까요?
감사합니다.

**Comment by minkikim89** [comment]
@nasyking 
arcus-hubble의 설정은 build(setup.sh 실행)를 하시기전에 env.sh에서 설정해주시면 됩니다. 이미 빌드를 끝낸 상황에서 바꾸시는 거라면 conf 디렉토리 밑의 파일들을 수정하시면 됩니다.

**Comment by diridiri** [comment]
안녕하세요 계속 빌드 관련 질문 드려 죄송합니다.
docker환경에서 ubuntu 12.04설치하여 arcus와 arcus-hubble을 세팅하였습니다. 

arcus에서 ./arcus.sh quicksetup conf/local.sample.json을 실행한 후 

```
$HOME/arcus/scripts/clearun_arcus.sh
sleep 3
$COLLECTD_HOME/sbin/collectd -C $COLLECTD_HOME/etc/collectd-listener-5s.conf
$COLLECTD_HOME/sbin/collectd -C $COLLECTD_HOME/etc/collectd-arcus.conf
$COLLECTD_HOME/sbin/collectd -C $COLLECTD_HOME/etc/collectd-arcus-prefix.conf
sleep 7
$ARCUS_HUBBLE_HOME/start.sh
```

의 쉘 스크립트를 실행하였습니다.

실행하면 Hubble은 아무 정보도 뜨지 않고 아래 사진과 같은 상태입니다.
￼
![image](https://cloud.githubusercontent.com/assets/8726370/15811761/7aabc33e-2be7-11e6-828d-adeac0faf2f1.png)

원인이라고 추측되는 에러 중 ~/.forever 디렉토리에 들어있는 로그파일중에 다음과 같은 에러가 있어 애를 먹고 있습니다.

```
module.js:442
    throw err;
    ^

Error: Cannot find module '/home/arcus/vendor/arcus-hubble/node_modules/zookeeper/lib/../build/default/zookeeper_native'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/arcus/vendor/arcus-hubble/node_modules/zookeeper/lib/zookeeper.js:5:18)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
error: Forever detected script exited with code: 1
```

찾아보니 node-gyp나 node-waf로 zookeeper를 빌드해야한다는데 혹시 알려주실 수 있나요?? 혹은 Hubble에 아무 정보가 뜨지 않는 문제를 해결할 방법이 있을까요??

아래 링크는 현재까지 빌드한 도커 파일입니다.
https://github.com/diridiri/kaist-open-source/blob/master/arcus-hubble/Dockerfile

감사합니다.

**Comment by minkikim89** [comment]
@diridiri 
https://github.com/naver/arcus-hubble#prerequisite
위에 링크를 타고 가보시면 node 0.10.28 버전을 사용하게 되어있는데 apt-get으로 설치하셨네요.
zookeeper 사용관련 모듈에 node-gyp가 사용되는데 최신 버전의 node에서는 이 빌드 툴을 사용하지 않아 생기는 문제입니다. 가이드 대로 설치하시면 될 것 같습니다.

**Comment by diridiri** [comment]
@minkikim89 
감사합니다. node 버전을 수정하고 나니 문제가 해결되었습니다.
하지만 아직 hubble에서 arcus stat을 비롯한 데이터가 아무것도 보이지 않습니다.
arcus에서 ./arcus.sh quicksetup conf/local.sample.json으로 실행하였고 .forever에는 딱히 에러로 보이는 로그는 없습니다.

도커파일과 arcus-hubble 실행 스크립트, arcus 실행 스크립트 공유해드립니다.
docker file : https://github.com/diridiri/kaist-open-source/blob/master/arcus-hubble/Dockerfile
arcus-hubble : https://github.com/diridiri/kaist-open-source/blob/master/arcus-hubble/clearun.sh
arcus: https://github.com/diridiri/kaist-open-source/blob/master/arcus-hubble/clearun_arcus.sh

감사합니다.

**Comment by minkikim89** [comment]
@diridiri 
https://github.com/naver/arcus-hubble#prerequisite
위 링크에서 보시면 /etc/hosts 설정에 대한 내용이 있습니다.
그 부분이 안되어있는 것 같네요. 한번 해보시고 다시 연락주세요.
